import {defineArrayMember, defineField, defineType} from 'sanity'

export const homePageType = defineType({
  name: 'homePage',
  title: 'Home Page',
  type: 'document',
  groups: [
    {name: 'hero', title: 'Hero', default: true},
    {name: 'content', title: 'Page content'},
    {name: 'visibility', title: 'Section visibility'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({name: 'eyebrow', title: 'Eyebrow', type: 'string', group: 'hero', validation: (rule) => rule.max(80)}),
    defineField({name: 'headline', title: 'Headline', type: 'string', group: 'hero', validation: (rule) => rule.required().max(100)}),
    defineField({name: 'supportingCopy', title: 'Supporting copy', type: 'text', rows: 3, group: 'hero', validation: (rule) => rule.required().max(240)}),
    defineField({name: 'primaryCta', title: 'Primary CTA', type: 'callToAction', group: 'hero'}),
    defineField({name: 'secondaryCta', title: 'Secondary CTA', type: 'callToAction', group: 'hero'}),
    defineField({name: 'introduction', title: 'Introduction', type: 'text', rows: 4, group: 'content', validation: (rule) => rule.max(500)}),
    defineField({name: 'presenceStatement', title: 'Presence statement', type: 'text', rows: 3, group: 'content', validation: (rule) => rule.max(240)}),
    defineField({name: 'trustHeading', title: 'Trust heading', type: 'string', group: 'content', validation: (rule) => rule.max(100)}),
    defineField({name: 'trustCopy', title: 'Trust copy', type: 'text', rows: 3, group: 'content', validation: (rule) => rule.max(300)}),
    defineField({
      name: 'trustPoints',
      title: 'Trust points',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'string'})],
      validation: (rule) => rule.max(6),
    }),
    defineField({name: 'workHeading', title: 'Selected work heading', type: 'string', group: 'content', validation: (rule) => rule.max(100)}),
    defineField({name: 'workCopy', title: 'Selected work copy', type: 'text', rows: 3, group: 'content', validation: (rule) => rule.max(260)}),
    defineField({
      name: 'selectedWork',
      title: 'Selected portfolio imagery',
      type: 'array',
      group: 'content',
      description: 'A small homepage-only selection. This is not a portfolio archive.',
      of: [defineArrayMember({type: 'imageWithAlt'})],
      validation: (rule) => rule.max(8),
    }),
    defineField({
      name: 'testimonials',
      title: 'Featured testimonials',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'reference', to: [{type: 'testimonial'}]})],
      validation: (rule) => rule.unique().max(4),
    }),
    defineField({name: 'closingHeading', title: 'Closing CTA heading', type: 'string', group: 'content', validation: (rule) => rule.max(100)}),
    defineField({name: 'closingCopy', title: 'Closing CTA copy', type: 'text', rows: 3, group: 'content', validation: (rule) => rule.max(240)}),
    defineField({name: 'showWork', title: 'Show selected work', type: 'boolean', group: 'visibility', initialValue: true}),
    defineField({name: 'showTrust', title: 'Show Why BASI', type: 'boolean', group: 'visibility', initialValue: true}),
    defineField({name: 'showTestimonials', title: 'Show published testimonials', type: 'boolean', group: 'visibility', initialValue: true}),
    defineField({name: 'seo', title: 'SEO', type: 'seo', group: 'seo'}),
  ],
  preview: {prepare: () => ({title: 'Home Page'})},
})
